spring:
  application:
    name: birthday
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

# Todo : secret_key 변경 후 환경변수 처리
jwt:
  secret_key: Y2hlZXNlYnVyZ2VyaXNiZXN0IQ==NlYnVyZ2VyaXNiZXN0IQ
  expiration-minutes: 15
  expiration-days: 7