spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;REFERENTIAL_INTEGRITY=true
    username: sa
    password: password
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

jwt:
  secret_key: Y2hlZXNlYnVyZ2VyaXNiZXN0IQ==NlYnVyZ2VyaXNiZXN0IQ
  expiration-minutes: 15
  expiration-days: 7