spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL;REFERENTIAL_INTEGRITY=true
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximum-pool-size: 5

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop