spring:
  application:
    name: birthday
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

# Todo : secret_key 변경 후 환경변수 처리
jwt:
  secret_key: Y2hlZXNlYnVyZ2VyaXNiZXN0IQ==NlYnVyZ2VyaXNiZXN0IQ
  expiration-minutes: 15
  expiration-days: 7